### ISSUE TITLE
Missing time and recurrence

### ISSUE THREAD

**Issue by balaramadurai** [anticodeninja/michel2#3]
Hello @anticodeninja,
  Thank you for rewrite. Your package helps me integrate Gmail with Tasks with Orgmode! Hurrah!

I would like to make a request for 2 features:
1. Support for time (which is a new addition to Google Tasks)
2. Support for recurrence (which is also a new addition to Google Tasks)

Thanks for your wonderful work with this code
Bala

**Comment by anticodeninja** [comment]
Hi @balaramadurai,

Thank you for your feedback. It is really good news because I lacked in such functionality. Unfortunately, after I have done some research it looks like this:

- Google Team still has not appended it to [Google Task API](https://developers.google.com/tasks/v1/reference/tasks).
- There are a few open issues on their tracker about it: [1](https://issuetracker.google.com/issues/128979662), [2](https://issuetracker.google.com/issues/131802538).
- Widget for Google Mail uses some internal proprietary RPC and cannot be helpfull here.

I will try to keep fingers on the pulse and implement these features as soon as Google Team appends them in the API.

Best Regards,
@anticodeninja

**Comment by balaramadurai** [comment]
Hmmm.. Thanks for your efforts. I guess there is nothing you can do per se.

I'll close this issue
Bala
