### ISSUE TITLE
Mail links lost

### ISSUE THREAD

**Issue by balaramadurai** [anticodeninja/michel2#4]
Hello @anticodeninja 
  The sync, pull and push work well for the basics. However, I seem to lose the linked mail if it is linked from Gmail. 

It'll be great if you can keep the linked Gmail linked.

Thanks and have a great day!
Bala

**Comment by anticodeninja** [comment]
Hi @balaramadurai,

Thank you for your feedback again.

Looks like a "pull" command is a little bit broken, but as it is just a wrapper for a "sync" command (now everything is a "sync" command) I've tried to reconstruct your issue with:

    touch test.org
    michel sync test.org "gtask://__default/test"
    vi test.org
    michel sync test.org "gtask://__default/test"

I have changed a task's title with the email links at the third step. After these steps, the links to emails in all tasks in this tasklist were kept. So, could you give me the whole and exact scenario which led to losing links? And, in your opinion, will it be a good addition to michel in case it keeps all the links as a task body?

Best Regards,
@anticodeninja

**Comment by balaramadurai** [comment]
Hi @anticodeninja 
  So, here's my workflow:

1. Open Gmail
2. Open an email for an action
3. Open the Google Tasks pane on the right side
4. Click on "Add a Task"
5. A task with the email link and the subject of the email opens
6. I set a time and date and sometimes change the task title
7. Perform `michel pull gtasks-email.org "gtask://__default/'@'email`

When I open `gtasks-email.org` in emacs. I see the scheduled day and that's it. There is no email link anywhere. The title is preserved.

However, when I perform `michel push gtasks-email.org "gtask://__default/'@'email` though, the email links in Google Tasks disappears, since there were no email links to begin with my org.

My thinking is that the push function works perfectly, there may be some issue in the pull.

I hope this helps
Bala

**Comment by anticodeninja** [comment]
Hi @balaramadurai 

Sorry i haven't replied earlier.

1. I supposed that you had some problems with `michel sync` command. For `michel push` it was quite an expected behavior because michel2 did not know anything about links. I tried to fix it in 17fc343, but...
2. It didn't help because Google Task API is such a mess :disappointed: Links aren't writable yet (https://issuetracker.google.com/issues/68982867) so it didn't solve the issue.
3. But, as now everything inside michel is really `sync` command, I re-implemented push-logic on the base of sync-logic, so it should work because it replaces `erase list - create a new one` semantic with `try to patch existed tree` and links should be kept if a task's name was not changed (or, at least, changed not so much). But in the worst cases it can lead to incorrect links association... But I hope it will happen very seldom and the latest patches will solve your issue and make you a little bit happier :slightly_smiling_face: 

p.s. I have heard that Google bug-tracker is quite useless, but it can be helpful if you starred both issues (from this issues and from #3) and leave comments in their bug-tracker.

Best Regards,
@anticodeninja

**Comment by balaramadurai** [comment]
Thanks @anticodeninja ,
  I guess we just have to wait for Google to get the act together on the Google Tasks thing.

Thanks for your efforts!
Bala
